# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _

ALPHA3_LANGDATA = (
    ("aar", _(u"Afar")),
    ("abk", _(u"Abkhazian")),
    ("ace", _(u"Achinese")),
    ("ach", _(u"Acoli")),
    ("ada", _(u"Adangme")),
    ("ady", _(u"Adyghe")),
    ("afh", _(u"Afrihili")),
    ("afr", _(u"Afrikaans")),
    ("ain", _(u"Ainu")),
    ("aka", _(u"Akan")),
    ("akk", _(u"Akkadian")),
    ("alb", _(u"Albanian")),
    ("ale", _(u"Aleut")),
    ("alt", _(u"Southern Altai")),
    ("amh", _(u"Amharic")),
    ("ang", _(u"English, Old (ca.450-1100)")),
    ("anp", _(u"Angika")),
    ("ara", _(u"Arabic")),
    ("arc", _(u"Official Aramaic (700-300 BCE)")),
    ("arg", _(u"Aragonese")),
    ("arm", _(u"Armenian")),
    ("arn", _(u"Mapudungun")),
    ("arp", _(u"Arapaho")),
    ("arw", _(u"Arawak")),
    ("asm", _(u"Assamese")),
    ("ast", _(u"Asturian")),
    ("ava", _(u"Avaric")),
    ("ave", _(u"Avestan")),
    ("awa", _(u"Awadhi")),
    ("aym", _(u"Aymara")),
    ("aze", _(u"Azerbaijani")),
    ("bak", _(u"Bashkir")),
    ("bal", _(u"Baluchi")),
    ("bam", _(u"Bambara")),
    ("ban", _(u"Balinese")),
    ("baq", _(u"Basque")),
    ("bas", _(u"Basa")),
    ("bej", _(u"Beja")),
    ("bel", _(u"Belarusian")),
    ("bem", _(u"Bemba")),
    ("ben", _(u"Bengali")),
    ("bho", _(u"Bhojpuri")),
    ("bik", _(u"Bikol")),
    ("bin", _(u"Bini")),
    ("bis", _(u"Bislama")),
    ("bla", _(u"Siksika")),
    ("bnt", _(u"Bantu (Other)")),
    ("bos", _(u"Bosnian")),
    ("bra", _(u"Braj")),
    ("bre", _(u"Breton")),
    ("bua", _(u"Buriat")),
    ("bug", _(u"Buginese")),
    ("bul", _(u"Bulgarian")),
    ("bur", _(u"Burmese")),
    ("byn", _(u"Blin")),
    ("cad", _(u"Caddo")),
    ("car", _(u"Galibi Carib")),
    ("cat", _(u"Catalan")),
    ("ceb", _(u"Cebuano")),
    ("cha", _(u"Chamorro")),
    ("chb", _(u"Chibcha")),
    ("che", _(u"Chechen")),
    ("chg", _(u"Chagatai")),
    ("chi", _(u"Chinese")),
    ("chk", _(u"Chuukese")),
    ("chm", _(u"Mari")),
    ("chn", _(u"Chinook jargon")),
    ("cho", _(u"Choctaw")),
    ("chp", _(u"Chipewyan")),
    ("chr", _(u"Cherokee")),
    ("chu", _(u"Church Slavic")),
    ("chv", _(u"Chuvash")),
    ("chy", _(u"Cheyenne")),
    ("cop", _(u"Coptic")),
    ("cor", _(u"Cornish")),
    ("cos", _(u"Corsican")),
    ("cpe", _(u"Creoles and pidgins, English based")),
    ("cpf", _(u"Creoles and pidgins, French-based ")),
    ("cpp", _(u"Creoles and pidgins, Portuguese-based ")),
    ("cre", _(u"Cree")),
    ("crh", _(u"Crimean Tatar")),
    ("crp", _(u"Creoles and pidgins ")),
    ("csb", _(u"Kashubian")),
    ("cze", _(u"Czech")),
    ("dak", _(u"Dakota")),
    ("dan", _(u"Danish")),
    ("dar", _(u"Dargwa")),
    ("del", _(u"Delaware")),
    ("den", _(u"Slave (Athapascan)")),
    ("dgr", _(u"Dogrib")),
    ("din", _(u"Dinka")),
    ("div", _(u"Divehi")),
    ("doi", _(u"Dogri")),
    ("dsb", _(u"Lower Sorbian")),
    ("dua", _(u"Duala")),
    ("dum", _(u"Dutch, Middle (ca.1050-1350)")),
    ("dut", _(u"Dutch")),
    ("dyu", _(u"Dyula")),
    ("dzo", _(u"Dzongkha")),
    ("efi", _(u"Efik")),
    ("egy", _(u"Egyptian (Ancient)")),
    ("eka", _(u"Ekajuk")),
    ("elx", _(u"Elamite")),
    ("eng", _(u"English")),
    ("enm", _(u"English, Middle (1100-1500)")),
    ("epo", _(u"Esperanto")),
    ("est", _(u"Estonian")),
    ("ewe", _(u"Ewe")),
    ("ewo", _(u"Ewondo")),
    ("fan", _(u"Fang")),
    ("fao", _(u"Faroese")),
    ("fat", _(u"Fanti")),
    ("fij", _(u"Fijian")),
    ("fil", _(u"Filipino")),
    ("fin", _(u"Finnish")),
    ("fon", _(u"Fon")),
    ("fre", _(u"French")),
    ("frm", _(u"French, Middle (ca.1400-1600)")),
    ("fro", _(u"French, Old (842-ca.1400)")),
    ("frr", _(u"Northern Frisian")),
    ("frs", _(u"Eastern Frisian")),
    ("fry", _(u"Western Frisian")),
    ("ful", _(u"Fulah")),
    ("fur", _(u"Friulian")),
    ("gaa", _(u"Ga")),
    ("gay", _(u"Gayo")),
    ("gba", _(u"Gbaya")),
    ("geo", _(u"Georgian")),
    ("ger", _(u"German")),
    ("gez", _(u"Geez")),
    ("gil", _(u"Gilbertese")),
    ("gla", _(u"Gaelic")),
    ("gle", _(u"Irish")),
    ("glg", _(u"Galician")),
    ("glv", _(u"Manx")),
    ("gmh", _(u"German, Middle High (ca.1050-1500)")),
    ("goh", _(u"German, Old High (ca.750-1050)")),
    ("gon", _(u"Gondi")),
    ("gor", _(u"Gorontalo")),
    ("got", _(u"Gothic")),
    ("grb", _(u"Grebo")),
    ("grc", _(u"Greek, Ancient (to 1453)")),
    ("gre", _(u"Greek, Modern (1453-)")),
    ("grn", _(u"Guarani")),
    ("gsw", _(u"Swiss German")),
    ("guj", _(u"Gujarati")),
    ("gwi", _(u"Gwich'in")),
    ("hai", _(u"Haida")),
    ("hat", _(u"Haitian")),
    ("hau", _(u"Hausa")),
    ("haw", _(u"Hawaiian")),
    ("heb", _(u"Hebrew")),
    ("her", _(u"Herero")),
    ("hil", _(u"Hiligaynon")),
    ("hin", _(u"Hindi")),
    ("hit", _(u"Hittite")),
    ("hmn", _(u"Hmong")),
    ("hmo", _(u"Hiri Motu")),
    ("hrv", _(u"Croatian")),
    ("hsb", _(u"Upper Sorbian")),
    ("hun", _(u"Hungarian")),
    ("hup", _(u"Hupa")),
    ("iba", _(u"Iban")),
    ("ibo", _(u"Igbo")),
    ("ice", _(u"Icelandic")),
    ("ido", _(u"Ido")),
    ("iii", _(u"Sichuan Yi")),
    ("iku", _(u"Inuktitut")),
    ("ile", _(u"Interlingue")),
    ("ilo", _(u"Iloko")),
    ("ina", _(u"Interlingua (International Auxiliary Language Association)")),
    ("ind", _(u"Indonesian")),
    ("inh", _(u"Ingush")),
    ("ipk", _(u"Inupiaq")),
    ("ita", _(u"Italian")),
    ("jav", _(u"Javanese")),
    ("jbo", _(u"Lojban")),
    ("jpn", _(u"Japanese")),
    ("jpr", _(u"Judeo-Persian")),
    ("jrb", _(u"Judeo-Arabic")),
    ("kaa", _(u"Kara-Kalpak")),
    ("kab", _(u"Kabyle")),
    ("kac", _(u"Kachin")),
    ("kal", _(u"Kalaallisut")),
    ("kam", _(u"Kamba")),
    ("kan", _(u"Kannada")),
    ("kas", _(u"Kashmiri")),
    ("kau", _(u"Kanuri")),
    ("kaw", _(u"Kawi")),
    ("kaz", _(u"Kazakh")),
    ("kbd", _(u"Kabardian")),
    ("kha", _(u"Khasi")),
    ("khm", _(u"Central Khmer")),
    ("kho", _(u"Khotanese")),
    ("kik", _(u"Kikuyu")),
    ("kin", _(u"Kinyarwanda")),
    ("kir", _(u"Kirghiz")),
    ("kmb", _(u"Kimbundu")),
    ("kok", _(u"Konkani")),
    ("kom", _(u"Komi")),
    ("kon", _(u"Kongo")),
    ("kor", _(u"Korean")),
    ("kos", _(u"Kosraean")),
    ("kpe", _(u"Kpelle")),
    ("krc", _(u"Karachay-Balkar")),
    ("krl", _(u"Karelian")),
    ("kru", _(u"Kurukh")),
    ("kua", _(u"Kuanyama")),
    ("kum", _(u"Kumyk")),
    ("kur", _(u"Kurdish")),
    ("kut", _(u"Kutenai")),
    ("lad", _(u"Ladino")),
    ("lah", _(u"Lahnda")),
    ("lam", _(u"Lamba")),
    ("lao", _(u"Lao")),
    ("lat", _(u"Latin")),
    ("lav", _(u"Latvian")),
    ("lez", _(u"Lezghian")),
    ("lim", _(u"Limburgan")),
    ("lin", _(u"Lingala")),
    ("lit", _(u"Lithuanian")),
    ("lol", _(u"Mongo")),
    ("loz", _(u"Lozi")),
    ("ltz", _(u"Luxembourgish")),
    ("lua", _(u"Luba-Lulua")),
    ("lub", _(u"Luba-Katanga")),
    ("lug", _(u"Ganda")),
    ("lui", _(u"Luiseno")),
    ("lun", _(u"Lunda")),
    ("luo", _(u"Luo (Kenya and Tanzania)")),
    ("lus", _(u"Lushai")),
    ("mac", _(u"Macedonian")),
    ("mad", _(u"Madurese")),
    ("mag", _(u"Magahi")),
    ("mah", _(u"Marshallese")),
    ("mai", _(u"Maithili")),
    ("mak", _(u"Makasar")),
    ("mal", _(u"Malayalam")),
    ("man", _(u"Mandingo")),
    ("mao", _(u"Maori")),
    ("mar", _(u"Marathi")),
    ("mas", _(u"Masai")),
    ("may", _(u"Malay")),
    ("mdf", _(u"Moksha")),
    ("mdr", _(u"Mandar")),
    ("men", _(u"Mende")),
    ("mga", _(u"Irish, Middle (900-1200)")),
    ("mic", _(u"Mi'kmaq")),
    ("min", _(u"Minangkabau")),
    ("mlg", _(u"Malagasy")),
    ("mlt", _(u"Maltese")),
    ("mnc", _(u"Manchu")),
    ("mni", _(u"Manipuri")),
    ("moh", _(u"Mohawk")),
    ("mon", _(u"Mongolian")),
    ("mos", _(u"Mossi")),
    ("mus", _(u"Creek")),
    ("mwl", _(u"Mirandese")),
    ("mwr", _(u"Marwari")),
    ("myv", _(u"Erzya")),
    ("nap", _(u"Neapolitan")),
    ("nau", _(u"Nauru")),
    ("nav", _(u"Navajo")),
    ("nbl", _(u"Ndebele, South")),
    ("nde", _(u"Ndebele, North")),
    ("ndo", _(u"Ndonga")),
    ("nds", _(u"Low German")),
    ("nep", _(u"Nepali")),
    ("new", _(u"Nepal Bhasa")),
    ("nia", _(u"Nias")),
    ("niu", _(u"Niuean")),
    ("nno", _(u"Norwegian Nynorsk")),
    ("nob", _(u"Bokmål, Norwegian")),
    ("nog", _(u"Nogai")),
    ("non", _(u"Norse, Old")),
    ("nor", _(u"Norwegian")),
    ("nqo", _(u"N'Ko")),
    ("nso", _(u"Pedi")),
    ("nwc", _(u"Classical Newari")),
    ("nya", _(u"Chichewa")),
    ("nym", _(u"Nyamwezi")),
    ("nyn", _(u"Nyankole")),
    ("nyo", _(u"Nyoro")),
    ("nzi", _(u"Nzima")),
    ("oci", _(u"Occitan (post 1500)")),
    ("oji", _(u"Ojibwa")),
    ("ori", _(u"Oriya")),
    ("orm", _(u"Oromo")),
    ("osa", _(u"Osage")),
    ("oss", _(u"Ossetian")),
    ("ota", _(u"Turkish, Ottoman (1500-1928)")),
    ("pag", _(u"Pangasinan")),
    ("pal", _(u"Pahlavi")),
    ("pam", _(u"Pampanga")),
    ("pan", _(u"Panjabi")),
    ("pap", _(u"Papiamento")),
    ("pau", _(u"Palauan")),
    ("peo", _(u"Persian, Old (ca.600-400 B.C.)")),
    ("per", _(u"Persian")),
    ("phn", _(u"Phoenician")),
    ("pli", _(u"Pali")),
    ("pol", _(u"Polish")),
    ("pon", _(u"Pohnpeian")),
    ("por", _(u"Portuguese")),
    ("pro", _(u"Provençal, Old (to 1500)")),
    ("pus", _(u"Pushto")),
    ("qaa-qtz", _(u"Reserved for local use")),
    ("que", _(u"Quechua")),
    ("raj", _(u"Rajasthani")),
    ("rap", _(u"Rapanui")),
    ("rar", _(u"Rarotongan")),
    ("roh", _(u"Romansh")),
    ("rom", _(u"Romany")),
    ("rum", _(u"Romanian")),
    ("run", _(u"Rundi")),
    ("rup", _(u"Aromanian")),
    ("rus", _(u"Russian")),
    ("sad", _(u"Sandawe")),
    ("sag", _(u"Sango")),
    ("sah", _(u"Yakut")),
    ("sai", _(u"South American Indian (Other)")),
    ("sam", _(u"Samaritan Aramaic")),
    ("san", _(u"Sanskrit")),
    ("sas", _(u"Sasak")),
    ("sat", _(u"Santali")),
    ("scn", _(u"Sicilian")),
    ("sco", _(u"Scots")),
    ("sel", _(u"Selkup")),
    ("sga", _(u"Irish, Old (to 900)")),
    ("sgn", _(u"Sign Languages")),
    ("shn", _(u"Shan")),
    ("sid", _(u"Sidamo")),
    ("sin", _(u"Sinhala")),
    ("slo", _(u"Slovak")),
    ("slv", _(u"Slovenian")),
    ("sma", _(u"Southern Sami")),
    ("sme", _(u"Northern Sami")),
    ("smj", _(u"Lule Sami")),
    ("smn", _(u"Inari Sami")),
    ("smo", _(u"Samoan")),
    ("sms", _(u"Skolt Sami")),
    ("sna", _(u"Shona")),
    ("snd", _(u"Sindhi")),
    ("snk", _(u"Soninke")),
    ("sog", _(u"Sogdian")),
    ("som", _(u"Somali")),
    ("sot", _(u"Sotho, Southern")),
    ("spa", _(u"Spanish")),
    ("srd", _(u"Sardinian")),
    ("srn", _(u"Sranan Tongo")),
    ("srp", _(u"Serbian")),
    ("srr", _(u"Serer")),
    ("ssw", _(u"Swati")),
    ("suk", _(u"Sukuma")),
    ("sun", _(u"Sundanese")),
    ("sus", _(u"Susu")),
    ("sux", _(u"Sumerian")),
    ("swa", _(u"Swahili")),
    ("swe", _(u"Swedish")),
    ("syc", _(u"Classical Syriac")),
    ("syr", _(u"Syriac")),
    ("tah", _(u"Tahitian")),
    ("tam", _(u"Tamil")),
    ("tat", _(u"Tatar")),
    ("tel", _(u"Telugu")),
    ("tem", _(u"Timne")),
    ("ter", _(u"Tereno")),
    ("tet", _(u"Tetum")),
    ("tgk", _(u"Tajik")),
    ("tgl", _(u"Tagalog")),
    ("tha", _(u"Thai")),
    ("tib", _(u"Tibetan")),
    ("tig", _(u"Tigre")),
    ("tir", _(u"Tigrinya")),
    ("tiv", _(u"Tiv")),
    ("tkl", _(u"Tokelau")),
    ("tlh", _(u"Klingon")),
    ("tli", _(u"Tlingit")),
    ("tmh", _(u"Tamashek")),
    ("tog", _(u"Tonga (Nyasa)")),
    ("ton", _(u"Tonga (Tonga Islands)")),
    ("tpi", _(u"Tok Pisin")),
    ("tsi", _(u"Tsimshian")),
    ("tsn", _(u"Tswana")),
    ("tso", _(u"Tsonga")),
    ("tuk", _(u"Turkmen")),
    ("tum", _(u"Tumbuka")),
    ("tur", _(u"Turkish")),
    ("tvl", _(u"Tuvalu")),
    ("twi", _(u"Twi")),
    ("tyv", _(u"Tuvinian")),
    ("udm", _(u"Udmurt")),
    ("uga", _(u"Ugaritic")),
    ("uig", _(u"Uighur")),
    ("ukr", _(u"Ukrainian")),
    ("umb", _(u"Umbundu")),
    ("und", _(u"Undetermined")),
    ("urd", _(u"Urdu")),
    ("uzb", _(u"Uzbek")),
    ("vai", _(u"Vai")),
    ("ven", _(u"Venda")),
    ("vie", _(u"Vietnamese")),
    ("vol", _(u"Volapük")),
    ("vot", _(u"Votic")),
    ("wal", _(u"Walamo")),
    ("war", _(u"Waray")),
    ("was", _(u"Washo")),
    ("wel", _(u"Welsh")),
    ("wln", _(u"Walloon")),
    ("wol", _(u"Wolof")),
    ("xal", _(u"Kalmyk")),
    ("xho", _(u"Xhosa")),
    ("yao", _(u"Yao")),
    ("yap", _(u"Yapese")),
    ("yid", _(u"Yiddish")),
    ("yor", _(u"Yoruba")),
    ("zap", _(u"Zapotec")),
    ("zbl", _(u"Blissymbols")),
    ("zen", _(u"Zenaga")),
    ("zgh", _(u"Standard Moroccan Tamazight")),
    ("zha", _(u"Zhuang")),
    ("zul", _(u"Zulu")),
    ("zun", _(u"Zuni")),
    ("zxx", _(u"No linguistic content")),
    ("zza", _(u"Zaza")),
)

