# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _

ALPHA23_LANGDATA = (
    ("aa", _(u"Afar")),
    ("ab", _(u"Abkhazian")),
    ("ace", _(u"Achinese")),
    ("ach", _(u"Acoli")),
    ("ada", _(u"Adangme")),
    ("ady", _(u"Adyghe")),
    ("afh", _(u"Afrihili")),
    ("af", _(u"Afrikaans")),
    ("ain", _(u"Ainu")),
    ("ak", _(u"Akan")),
    ("akk", _(u"Akkadian")),
    ("sq", _(u"Albanian")),
    ("ale", _(u"Aleut")),
    ("alt", _(u"Southern Altai")),
    ("am", _(u"Amharic")),
    ("ang", _(u"English, Old (ca.450-1100)")),
    ("anp", _(u"Angika")),
    ("ar", _(u"Arabic")),
    ("arc", _(u"Official Aramaic (700-300 BCE)")),
    ("an", _(u"Aragonese")),
    ("hy", _(u"Armenian")),
    ("arn", _(u"Mapudungun")),
    ("arp", _(u"Arapaho")),
    ("arw", _(u"Arawak")),
    ("as", _(u"Assamese")),
    ("ast", _(u"Asturian")),
    ("av", _(u"Avaric")),
    ("ae", _(u"Avestan")),
    ("awa", _(u"Awadhi")),
    ("ay", _(u"Aymara")),
    ("az", _(u"Azerbaijani")),
    ("ba", _(u"Bashkir")),
    ("bal", _(u"Baluchi")),
    ("bm", _(u"Bambara")),
    ("ban", _(u"Balinese")),
    ("eu", _(u"Basque")),
    ("bas", _(u"Basa")),
    ("bej", _(u"Beja")),
    ("be", _(u"Belarusian")),
    ("bem", _(u"Bemba")),
    ("bn", _(u"Bengali")),
    ("bho", _(u"Bhojpuri")),
    ("bik", _(u"Bikol")),
    ("bin", _(u"Bini")),
    ("bi", _(u"Bislama")),
    ("bla", _(u"Siksika")),
    ("bnt", _(u"Bantu (Other)")),
    ("bs", _(u"Bosnian")),
    ("bra", _(u"Braj")),
    ("br", _(u"Breton")),
    ("bua", _(u"Buriat")),
    ("bug", _(u"Buginese")),
    ("bg", _(u"Bulgarian")),
    ("my", _(u"Burmese")),
    ("byn", _(u"Blin")),
    ("cad", _(u"Caddo")),
    ("car", _(u"Galibi Carib")),
    ("ca", _(u"Catalan")),
    ("ceb", _(u"Cebuano")),
    ("ch", _(u"Chamorro")),
    ("chb", _(u"Chibcha")),
    ("ce", _(u"Chechen")),
    ("chg", _(u"Chagatai")),
    ("zh", _(u"Chinese")),
    ("chk", _(u"Chuukese")),
    ("chm", _(u"Mari")),
    ("chn", _(u"Chinook jargon")),
    ("cho", _(u"Choctaw")),
    ("chp", _(u"Chipewyan")),
    ("chr", _(u"Cherokee")),
    ("cu", _(u"Church Slavic")),
    ("cv", _(u"Chuvash")),
    ("chy", _(u"Cheyenne")),
    ("cop", _(u"Coptic")),
    ("kw", _(u"Cornish")),
    ("co", _(u"Corsican")),
    ("cpe", _(u"Creoles and pidgins, English based")),
    ("cpf", _(u"Creoles and pidgins, French-based ")),
    ("cpp", _(u"Creoles and pidgins, Portuguese-based ")),
    ("cr", _(u"Cree")),
    ("crh", _(u"Crimean Tatar")),
    ("crp", _(u"Creoles and pidgins ")),
    ("csb", _(u"Kashubian")),
    ("cs", _(u"Czech")),
    ("dak", _(u"Dakota")),
    ("da", _(u"Danish")),
    ("dar", _(u"Dargwa")),
    ("del", _(u"Delaware")),
    ("den", _(u"Slave (Athapascan)")),
    ("dgr", _(u"Dogrib")),
    ("din", _(u"Dinka")),
    ("dv", _(u"Divehi")),
    ("doi", _(u"Dogri")),
    ("dsb", _(u"Lower Sorbian")),
    ("dua", _(u"Duala")),
    ("dum", _(u"Dutch, Middle (ca.1050-1350)")),
    ("nl", _(u"Dutch")),
    ("dyu", _(u"Dyula")),
    ("dz", _(u"Dzongkha")),
    ("efi", _(u"Efik")),
    ("egy", _(u"Egyptian (Ancient)")),
    ("eka", _(u"Ekajuk")),
    ("elx", _(u"Elamite")),
    ("en", _(u"English")),
    ("enm", _(u"English, Middle (1100-1500)")),
    ("eo", _(u"Esperanto")),
    ("et", _(u"Estonian")),
    ("ee", _(u"Ewe")),
    ("ewo", _(u"Ewondo")),
    ("fan", _(u"Fang")),
    ("fo", _(u"Faroese")),
    ("fat", _(u"Fanti")),
    ("fj", _(u"Fijian")),
    ("fil", _(u"Filipino")),
    ("fi", _(u"Finnish")),
    ("fon", _(u"Fon")),
    ("fr", _(u"French")),
    ("frm", _(u"French, Middle (ca.1400-1600)")),
    ("fro", _(u"French, Old (842-ca.1400)")),
    ("frr", _(u"Northern Frisian")),
    ("frs", _(u"Eastern Frisian")),
    ("fy", _(u"Western Frisian")),
    ("ff", _(u"Fulah")),
    ("fur", _(u"Friulian")),
    ("gaa", _(u"Ga")),
    ("gay", _(u"Gayo")),
    ("gba", _(u"Gbaya")),
    ("ka", _(u"Georgian")),
    ("de", _(u"German")),
    ("gez", _(u"Geez")),
    ("gil", _(u"Gilbertese")),
    ("gd", _(u"Gaelic")),
    ("ga", _(u"Irish")),
    ("gl", _(u"Galician")),
    ("gv", _(u"Manx")),
    ("gmh", _(u"German, Middle High (ca.1050-1500)")),
    ("goh", _(u"German, Old High (ca.750-1050)")),
    ("gon", _(u"Gondi")),
    ("gor", _(u"Gorontalo")),
    ("got", _(u"Gothic")),
    ("grb", _(u"Grebo")),
    ("grc", _(u"Greek, Ancient (to 1453)")),
    ("el", _(u"Greek, Modern (1453-)")),
    ("gn", _(u"Guarani")),
    ("gsw", _(u"Swiss German")),
    ("gu", _(u"Gujarati")),
    ("gwi", _(u"Gwich'in")),
    ("hai", _(u"Haida")),
    ("ht", _(u"Haitian")),
    ("ha", _(u"Hausa")),
    ("haw", _(u"Hawaiian")),
    ("he", _(u"Hebrew")),
    ("hz", _(u"Herero")),
    ("hil", _(u"Hiligaynon")),
    ("hi", _(u"Hindi")),
    ("hit", _(u"Hittite")),
    ("hmn", _(u"Hmong")),
    ("ho", _(u"Hiri Motu")),
    ("hr", _(u"Croatian")),
    ("hsb", _(u"Upper Sorbian")),
    ("hu", _(u"Hungarian")),
    ("hup", _(u"Hupa")),
    ("iba", _(u"Iban")),
    ("ig", _(u"Igbo")),
    ("is", _(u"Icelandic")),
    ("io", _(u"Ido")),
    ("ii", _(u"Sichuan Yi")),
    ("iu", _(u"Inuktitut")),
    ("ie", _(u"Interlingue")),
    ("ilo", _(u"Iloko")),
    ("ia", _(u"Interlingua (International Auxiliary Language Association)")),
    ("id", _(u"Indonesian")),
    ("inh", _(u"Ingush")),
    ("ik", _(u"Inupiaq")),
    ("it", _(u"Italian")),
    ("jv", _(u"Javanese")),
    ("jbo", _(u"Lojban")),
    ("ja", _(u"Japanese")),
    ("jpr", _(u"Judeo-Persian")),
    ("jrb", _(u"Judeo-Arabic")),
    ("kaa", _(u"Kara-Kalpak")),
    ("kab", _(u"Kabyle")),
    ("kac", _(u"Kachin")),
    ("kl", _(u"Kalaallisut")),
    ("kam", _(u"Kamba")),
    ("kn", _(u"Kannada")),
    ("ks", _(u"Kashmiri")),
    ("kr", _(u"Kanuri")),
    ("kaw", _(u"Kawi")),
    ("kk", _(u"Kazakh")),
    ("kbd", _(u"Kabardian")),
    ("kha", _(u"Khasi")),
    ("km", _(u"Central Khmer")),
    ("kho", _(u"Khotanese")),
    ("ki", _(u"Kikuyu")),
    ("rw", _(u"Kinyarwanda")),
    ("ky", _(u"Kirghiz")),
    ("kmb", _(u"Kimbundu")),
    ("kok", _(u"Konkani")),
    ("kv", _(u"Komi")),
    ("kg", _(u"Kongo")),
    ("ko", _(u"Korean")),
    ("kos", _(u"Kosraean")),
    ("kpe", _(u"Kpelle")),
    ("krc", _(u"Karachay-Balkar")),
    ("krl", _(u"Karelian")),
    ("kru", _(u"Kurukh")),
    ("kj", _(u"Kuanyama")),
    ("kum", _(u"Kumyk")),
    ("ku", _(u"Kurdish")),
    ("kut", _(u"Kutenai")),
    ("lad", _(u"Ladino")),
    ("lah", _(u"Lahnda")),
    ("lam", _(u"Lamba")),
    ("lo", _(u"Lao")),
    ("la", _(u"Latin")),
    ("lv", _(u"Latvian")),
    ("lez", _(u"Lezghian")),
    ("li", _(u"Limburgan")),
    ("ln", _(u"Lingala")),
    ("lt", _(u"Lithuanian")),
    ("lol", _(u"Mongo")),
    ("loz", _(u"Lozi")),
    ("lb", _(u"Luxembourgish")),
    ("lua", _(u"Luba-Lulua")),
    ("lu", _(u"Luba-Katanga")),
    ("lg", _(u"Ganda")),
    ("lui", _(u"Luiseno")),
    ("lun", _(u"Lunda")),
    ("luo", _(u"Luo (Kenya and Tanzania)")),
    ("lus", _(u"Lushai")),
    ("mk", _(u"Macedonian")),
    ("mad", _(u"Madurese")),
    ("mag", _(u"Magahi")),
    ("mh", _(u"Marshallese")),
    ("mai", _(u"Maithili")),
    ("mak", _(u"Makasar")),
    ("ml", _(u"Malayalam")),
    ("man", _(u"Mandingo")),
    ("mi", _(u"Maori")),
    ("mr", _(u"Marathi")),
    ("mas", _(u"Masai")),
    ("ms", _(u"Malay")),
    ("mdf", _(u"Moksha")),
    ("mdr", _(u"Mandar")),
    ("men", _(u"Mende")),
    ("mga", _(u"Irish, Middle (900-1200)")),
    ("mic", _(u"Mi'kmaq")),
    ("min", _(u"Minangkabau")),
    ("mg", _(u"Malagasy")),
    ("mt", _(u"Maltese")),
    ("mnc", _(u"Manchu")),
    ("mni", _(u"Manipuri")),
    ("moh", _(u"Mohawk")),
    ("mn", _(u"Mongolian")),
    ("mos", _(u"Mossi")),
    ("mus", _(u"Creek")),
    ("mwl", _(u"Mirandese")),
    ("mwr", _(u"Marwari")),
    ("myv", _(u"Erzya")),
    ("nap", _(u"Neapolitan")),
    ("na", _(u"Nauru")),
    ("nv", _(u"Navajo")),
    ("nr", _(u"Ndebele, South")),
    ("nd", _(u"Ndebele, North")),
    ("ng", _(u"Ndonga")),
    ("nds", _(u"Low German")),
    ("ne", _(u"Nepali")),
    ("new", _(u"Nepal Bhasa")),
    ("nia", _(u"Nias")),
    ("niu", _(u"Niuean")),
    ("nn", _(u"Norwegian Nynorsk")),
    ("nb", _(u"Bokmål, Norwegian")),
    ("nog", _(u"Nogai")),
    ("non", _(u"Norse, Old")),
    ("no", _(u"Norwegian")),
    ("nqo", _(u"N'Ko")),
    ("nso", _(u"Pedi")),
    ("nwc", _(u"Classical Newari")),
    ("ny", _(u"Chichewa")),
    ("nym", _(u"Nyamwezi")),
    ("nyn", _(u"Nyankole")),
    ("nyo", _(u"Nyoro")),
    ("nzi", _(u"Nzima")),
    ("oc", _(u"Occitan (post 1500)")),
    ("oj", _(u"Ojibwa")),
    ("or", _(u"Oriya")),
    ("om", _(u"Oromo")),
    ("osa", _(u"Osage")),
    ("os", _(u"Ossetian")),
    ("ota", _(u"Turkish, Ottoman (1500-1928)")),
    ("pag", _(u"Pangasinan")),
    ("pal", _(u"Pahlavi")),
    ("pam", _(u"Pampanga")),
    ("pa", _(u"Panjabi")),
    ("pap", _(u"Papiamento")),
    ("pau", _(u"Palauan")),
    ("peo", _(u"Persian, Old (ca.600-400 B.C.)")),
    ("fa", _(u"Persian")),
    ("phn", _(u"Phoenician")),
    ("pi", _(u"Pali")),
    ("pl", _(u"Polish")),
    ("pon", _(u"Pohnpeian")),
    ("pt", _(u"Portuguese")),
    ("pro", _(u"Provençal, Old (to 1500)")),
    ("ps", _(u"Pushto")),
    ("qaa-qtz", _(u"Reserved for local use")),
    ("qu", _(u"Quechua")),
    ("raj", _(u"Rajasthani")),
    ("rap", _(u"Rapanui")),
    ("rar", _(u"Rarotongan")),
    ("rm", _(u"Romansh")),
    ("rom", _(u"Romany")),
    ("ro", _(u"Romanian")),
    ("rn", _(u"Rundi")),
    ("rup", _(u"Aromanian")),
    ("ru", _(u"Russian")),
    ("sad", _(u"Sandawe")),
    ("sg", _(u"Sango")),
    ("sah", _(u"Yakut")),
    ("sai", _(u"South American Indian (Other)")),
    ("sam", _(u"Samaritan Aramaic")),
    ("sa", _(u"Sanskrit")),
    ("sas", _(u"Sasak")),
    ("sat", _(u"Santali")),
    ("scn", _(u"Sicilian")),
    ("sco", _(u"Scots")),
    ("sel", _(u"Selkup")),
    ("sga", _(u"Irish, Old (to 900)")),
    ("sgn", _(u"Sign Languages")),
    ("shn", _(u"Shan")),
    ("sid", _(u"Sidamo")),
    ("si", _(u"Sinhala")),
    ("sk", _(u"Slovak")),
    ("sl", _(u"Slovenian")),
    ("sma", _(u"Southern Sami")),
    ("se", _(u"Northern Sami")),
    ("smj", _(u"Lule Sami")),
    ("smn", _(u"Inari Sami")),
    ("sm", _(u"Samoan")),
    ("sms", _(u"Skolt Sami")),
    ("sn", _(u"Shona")),
    ("sd", _(u"Sindhi")),
    ("snk", _(u"Soninke")),
    ("sog", _(u"Sogdian")),
    ("so", _(u"Somali")),
    ("st", _(u"Sotho, Southern")),
    ("es", _(u"Spanish")),
    ("sc", _(u"Sardinian")),
    ("srn", _(u"Sranan Tongo")),
    ("sr", _(u"Serbian")),
    ("srr", _(u"Serer")),
    ("ss", _(u"Swati")),
    ("suk", _(u"Sukuma")),
    ("su", _(u"Sundanese")),
    ("sus", _(u"Susu")),
    ("sux", _(u"Sumerian")),
    ("sw", _(u"Swahili")),
    ("sv", _(u"Swedish")),
    ("syc", _(u"Classical Syriac")),
    ("syr", _(u"Syriac")),
    ("ty", _(u"Tahitian")),
    ("ta", _(u"Tamil")),
    ("tt", _(u"Tatar")),
    ("te", _(u"Telugu")),
    ("tem", _(u"Timne")),
    ("ter", _(u"Tereno")),
    ("tet", _(u"Tetum")),
    ("tg", _(u"Tajik")),
    ("tl", _(u"Tagalog")),
    ("th", _(u"Thai")),
    ("bo", _(u"Tibetan")),
    ("tig", _(u"Tigre")),
    ("ti", _(u"Tigrinya")),
    ("tiv", _(u"Tiv")),
    ("tkl", _(u"Tokelau")),
    ("tlh", _(u"Klingon")),
    ("tli", _(u"Tlingit")),
    ("tmh", _(u"Tamashek")),
    ("tog", _(u"Tonga (Nyasa)")),
    ("to", _(u"Tonga (Tonga Islands)")),
    ("tpi", _(u"Tok Pisin")),
    ("tsi", _(u"Tsimshian")),
    ("tn", _(u"Tswana")),
    ("ts", _(u"Tsonga")),
    ("tk", _(u"Turkmen")),
    ("tum", _(u"Tumbuka")),
    ("tr", _(u"Turkish")),
    ("tvl", _(u"Tuvalu")),
    ("tw", _(u"Twi")),
    ("tyv", _(u"Tuvinian")),
    ("udm", _(u"Udmurt")),
    ("uga", _(u"Ugaritic")),
    ("ug", _(u"Uighur")),
    ("uk", _(u"Ukrainian")),
    ("umb", _(u"Umbundu")),
    ("und", _(u"Undetermined")),
    ("ur", _(u"Urdu")),
    ("uz", _(u"Uzbek")),
    ("vai", _(u"Vai")),
    ("ve", _(u"Venda")),
    ("vi", _(u"Vietnamese")),
    ("vo", _(u"Volapük")),
    ("vot", _(u"Votic")),
    ("wal", _(u"Walamo")),
    ("war", _(u"Waray")),
    ("was", _(u"Washo")),
    ("cy", _(u"Welsh")),
    ("wa", _(u"Walloon")),
    ("wo", _(u"Wolof")),
    ("xal", _(u"Kalmyk")),
    ("xh", _(u"Xhosa")),
    ("yao", _(u"Yao")),
    ("yap", _(u"Yapese")),
    ("yi", _(u"Yiddish")),
    ("yo", _(u"Yoruba")),
    ("zap", _(u"Zapotec")),
    ("zbl", _(u"Blissymbols")),
    ("zen", _(u"Zenaga")),
    ("zgh", _(u"Standard Moroccan Tamazight")),
    ("za", _(u"Zhuang")),
    ("zu", _(u"Zulu")),
    ("zun", _(u"Zuni")),
    ("zxx", _(u"No linguistic content")),
    ("zza", _(u"Zaza")),
)

